//let a = 5 -> o erro acontece pois "a" não está declarado

try{
    let b = a * 2
} catch(e){
    console.log(e)
}